### ISSUE TITLE
need urgency help menu_item_set_icon_always_visible undefined reference

### ISSUE THREAD

**Issue by mckaygerhard** [lpereira/hardinfo#2]
> libhardinfo-shell.a(shell.c.o): In function `menu_item_set_icon_always_visible':
> /media/DATASUPER/MASSENKOH-new/MASSENKOH-REPO/mskcommon/desktop/hardinfo/hardinfo-0.5.1+20120601/shell/shell.c:506: undefined reference to`gtk_image_menu_item_set_always_show_image'

searching in api http://developer.gnome.org/gtk/2.24/GtkImageMenuItem.html#gtk-image-menu-item-set-always-show-image seems that hardinfo need gtk 2.18 as minimun,

documentation said this since 2.16 but failds.. i use 2.16 and dont work.
 i need to kwon how to disable this funtion or workaround for build with gtk 2.16 please

commented the lines compiles, due the function only forces menu loading, its commonly utility as i read..
